# version: '3.8'

services:
  # Application Service (shop-backend)
  app:
    build: .  # Build the image from Dockerfile
    container_name: shop-backend
    ports:
      - "8080:8080"  # Expose app on port 8080
    environment:
      - DATABASE_URL=postgres://test:test@db:5432/shopdb  # Connection string for the database
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
    command: ["./shop-backend"]  # Ensure app starts after being built

  # PostgreSQL Service
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test", "-d", "shopdb", "-h", "db"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

# Volumes for persisting data
volumes:
  postgres-data:
    driver: local
