name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main  
      - ci_action
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest  # The runner to execute the jobs (Ubuntu in this case)
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This action checks out your repository so that the Docker image can be built

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # This action sets up Docker Buildx to perform multi-platform builds

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
        registry: ghcr.io 
        
    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/shop-backend:latest .  

    - name: Push the Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/shop-backend:latest 

