name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main  
      - ci_action
      - ci-test
    tags:
      - 'v*' 

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: shopdb
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U test" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'  # Specify the Go version you're using

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run unit tests
      run: |
        go test -v -cover ./...
      env:
        # Set environment variables for database connection
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USER: test
        DB_PASSWORD: test
        DB_NAME: shopdb

  # Job for Building and Pushing Docker Image
  build:
    runs-on: ubuntu-latest  
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This action checks out your repository so that the Docker image can be built

    - name: Print GitHub context for tagging
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "CI triggered by tag: ${GITHUB_REF#refs/tags/}"        
        elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
          TAG_NAME=${GITHUB_SHA:0:5}
          echo "CI triggered by commit SHA (first 5 chars): ${GITHUB_SHA:0:5}"
        fi
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # This action sets up Docker Buildx to perform multi-platform builds

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
        registry: ghcr.io 
        
    - name: Build the Docker image
      run: |
        docker build  --build-arg CONFIG_FILE=${{ env.CONFIG_FILE }}  -t ghcr.io/${{ github.repository }}/shop-backend:$TAG_NAME -t ghcr.io/${{ github.repository }}/shop-backend:latest   .  
      env:
        CONFIG_FILE: config/action.yaml   

    - name: Push the Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/shop-backend:$TAG_NAME 
        docker push ghcr.io/${{ github.repository }}/shop-backend:latest

